set nocompatible		" required
filetype off			" required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"  call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions fo Vundle
" used Bundle instead of plugin)
Plugin 'vim-scripts/indentpython.vim'
"Plugin 'vim-syntastic/syntastic'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'mattn/vim-lsp-settings'
Plugin 'nvie/vim-flake8'
"Plugin 'scrooloose/nerdtree'
"Plugin 'jistr/vim-nerdtree-tabs'
"Plugin 'Lokaltog/powerline'
"Plugin 'jiangmiao/auto-pairs'
"Plugin 'mattn/emmet-vim'
"Plugin yggdroot/indentLine'
"Plugin 'yuezk/vim-js'
"Plugin 'maxmellon/vim-jsx-pretty'
"Plugin 'tpope/vim-commentary'
"Plugin 'w0rp/ale'

" ...

" All of your plugins must be added before the following line
call vundle#end()		" required
filetype plugin indent on	" required

" Enable folding
set foldmethod=indent
set foldlevel=99

function! s:on_lsp_buffer_enabled() abort
	setlocal omnifunc=lsp#complete
endfunction

augroup lsp_install
	au!
	autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

au BufNewFile,BufRead *.py
	\set tabstop=4
	\set softtabstop=4
	\set shiftwidth=4
	\set textwidth=79
	\set expandtab
	\set autoindent
	\set fileformat=unix

au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\s+$/

set encoding=utf-8

highlight BadWhitespace ctermbg=red guibg=darkred
" let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

let python_highlight_all=1
syntax on



set number
set showmatch
set smartcase
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc
set visualbell
set noerrorbells
